apiVersion: v1
kind: Pod
metadata:
  name: stress-612workstation
  namespace: stress
spec:
  nodeName: 612workstation
  containers:
    - name: stress
      image: progrium/stress
      command: ["stress"]
      args: ["--cpu", "10", "--vm", "1", "--vm-bytes", "31990M", "--timeout", "300s"]
      resources:
        limits:
          cpu: "10"
          memory: "32Gi"

---

apiVersion: v1
kind: Pod
metadata:
  name: stress-612notebook
  namespace: default
spec:
  nodeName: 612notebook
  containers:
    - name: stress
      image: progrium/stress
      command: ["stress"]
      args: ["--cpu", "4", "--vm", "1", "--vm-bytes", "3807M", "--timeout", "300s"]
      resources:
        limits:
          cpu: "4"
          memory: "4Gi"

---

apiVersion: v1
kind: Pod
metadata:
  name: stress-ic-laptop1
  namespace: default
spec:
  nodeName: ic-laptop1
  containers:
    - name: stress
      image: progrium/stress
      command: ["stress"]
      args: ["--cpu", "10", "--vm", "1", "--vm-bytes", "15827M", "--timeout", "300s"]
      resources:
        limits:
          cpu: "10"
          memory: "16Gi"

