apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-farm
  namespace: didimdol
data:
  SIM_MODE: VIRTUAL_TIME
  TYPE: smart_farm
  WORKING_TIME: "60"
  TARGET_PRODUCTION: "30"
  FAILURE_RATE: "0.3"
  DEFAULT_PRODUCTION_RATE: "5"
  CHECK_PRODUCTION_RATE: "2.5"
  SIMULATION_TIME_STEP: "2"
  ACCUMULATED_DEFECT_RATE: "0.02"

---

apiVersion: v1
kind: Pod
metadata:
  name: smart-farm-simulator
  namespace: didimdol
spec:
  containers:
    - name: simulator
      image: bodlehg/didimdol:smart_farm
      imagePullPolicy: Always
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      envFrom:
      - configMapRef:
          name: smart-farm
      resources:
        requests:
          memory: "2Gi"
          cpu: 2
        limits:
          memory: "4Gi"
          cpu: 4
  restartPolicy: Never